services:
  next:
    build: .
    container_name: next
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: