services:
  next:
    build: .
    container_name: next
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:p%40ssw0rd@mongo-db:27017/quicklinkdb?authSource=admin
      - NEXT_PUBLIC_DOMAIN=http://localhost:3000
      - MONGODB_COLLECTION=files
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - NEXTJS_IGNORE_ESLINT=1
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd
      MONGO_INITDB_DATABASE: quicklinkdb
    command: [ "mongod","--auth" ]

volumes:
  mongo-data: